<?php
/**
 * Do not edit this file. Edit the config files found in {{ path('config-dir', 'wpconfig-dir') }}/ instead.
 */

require_once(__DIR__ . '/{{ path('vendor-dir', 'wordpress.wpconfig-dir') }}/wordpress-autoload.php');


/** Absolute path to the WordPress directory. */
if (!defined('ABSPATH')) {
	define('ABSPATH', __DIR__ . '/{{ path('wordpress.install-dir', 'vendor-dir') }}/');
}

require_once(ABSPATH . 'wp-settings.php');
