name: Static Analysis
on:
    push:
    pull_request:

jobs:
    phpstan:
        runs-on: ubuntu-latest
        name: PHP Static Analysis
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.0"
            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                  timeout_minutes: 10
                  max_attempts: 3
                  command: composer install --no-interaction
            - name: Run Script
              run: composer phpstan
